-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 12:01:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SuperHeroDB_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SuperHeroDB_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuperHeroDB_test` DEFAULT CHARACTER SET utf8 ;
USE `SuperHeroDB_test` ;

-- -----------------------------------------------------
-- Table `SuperHeroDB_test`.`Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Hero` (
  `idHero` INT NOT NULL AUTO_INCREMENT,
  `nameHero` VARCHAR(45) NOT NULL,
  `descriptionHero` VARCHAR(45) NULL,
  `powerHero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperHeroDB__test`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `nameLocation` VARCHAR(45) NOT NULL,
  `descriptionLocation` VARCHAR(45) NULL,
  `addressLocation` VARCHAR(45) NOT NULL,
  `coordinates` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperHeroDB`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Organization` (
  `idOrganization` INT NOT NULL AUTO_INCREMENT,
  `nameOrg` VARCHAR(45) NOT NULL,
  `descriptionOrg` VARCHAR(45) NULL,
  `contactInfoOrg` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrganization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperHeroDB`.`Sighting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Sighting` (
  `idSighSighting` INT NOT NULL AUTO_INCREMENT,
  `dateSighting` DATE NULL,
  `Location_idLocation` INT NOT NULL,
  PRIMARY KEY (`idSighSighting`, `Location_idLocation`),
  INDEX `fk_Sighting_Location1_idx` (`Location_idLocation` ASC) VISIBLE,
  CONSTRAINT `fk_Sighting_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `SuperHeroDB_test`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperHeroDB_test`.`Hero_has_Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Hero_has_Organization` (
  `idHeroOrg` INT NOT NULL AUTO_INCREMENT,
  `Hero_idHero` INT NOT NULL,
  `Organization_idOrganization` INT NOT NULL,
  PRIMARY KEY (`idHeroOrg`, `Hero_idHero`, `Organization_idOrganization`),
  INDEX `fk_Hero_has_Organization_Organization1_idx` (`Organization_idOrganization` ASC) VISIBLE,
  INDEX `fk_Hero_has_Organization_Hero1_idx` (`Hero_idHero` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_Organization_Hero1`
    FOREIGN KEY (`Hero_idHero`)
    REFERENCES `SuperHeroDB_test`.`Hero` (`idHero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_Organization_Organization1`
    FOREIGN KEY (`Organization_idOrganization`)
    REFERENCES `SuperHeroDB_test`.`Organization` (`idOrganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperHeroDB_test`.`Sighting_has_Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperHeroDB_test`.`Sighting_has_Hero` (
  `idSightingHero` INT NOT NULL AUTO_INCREMENT,
  `Sighting_idSighSighting` INT NOT NULL,
  `Hero_idHero` INT NOT NULL,
  PRIMARY KEY (`idSightingHero`, `Sighting_idSighSighting`, `Hero_idHero`),
  INDEX `fk_Sighting_has_Hero_Hero1_idx` (`Hero_idHero` ASC) VISIBLE,
  INDEX `fk_Sighting_has_Hero_Sighting1_idx` (`Sighting_idSighSighting` ASC) VISIBLE,
  CONSTRAINT `fk_Sighting_has_Hero_Sighting1`
    FOREIGN KEY (`Sighting_idSighSighting`)
    REFERENCES `SuperHeroDB_test`.`Sighting` (`idSighSighting`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sighting_has_Hero_Hero1`
    FOREIGN KEY (`Hero_idHero`)
    REFERENCES `SuperHeroDB_test`.`Hero` (`idHero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
